### ISSUE TITLE
Copying files into media folder causes crash

### ISSUE THREAD

**Issue by Somebodyisnobody** [ChristophSilge/TipToiGui#1]
Steps to reproduce:
 - Open Project
 - Copy file into `Audio/` (the media folder) of the opened project

Produces:

> System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.
  Quelle = System.Windows.Forms
  Stapelüberwachung:
   bei System.Windows.Forms.Control.get_Handle()
   bei System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)
   bei System.Windows.Forms.ComboBox.NativeClear()
   bei System.Windows.Forms.ComboBox.ObjectCollection.ClearInternal()
   bei TipToyGui.Nodes.MediaNode.Sfw_Changed(Object sender, FileSystemEventArgs e) in [...]\TipToiGui\TipToyGui\Nodes\MediaNode.cs: Zeile93
   bei System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   bei System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   bei System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

>  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:

>    System.Windows.Forms.Control.Handle.get()
    System.Windows.Forms.Control.SendMessage(int, int, int)
    System.Windows.Forms.ComboBox.NativeClear()
    System.Windows.Forms.ComboBox.ObjectCollection.ClearInternal()
    TipToyGui.Nodes.MediaNode.Sfw_Changed(object, System.IO.FileSystemEventArgs) in MediaNode.cs
    System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
    System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(int, string)
    System.IO.FileSystemWatcher.CompletionStatusChanged(uint, uint, System.Threading.NativeOverlapped*)
    System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint, uint, System.Threading.NativeOverlapped*)

Can this be solved by surrounding with try/catch?

**Comment by nub1604** [comment]
I have reproduced this issue and I have fixed it with "invoke" the method

**Comment by nub1604** [comment]
I've pushed a new version and it seems to work properly now
