### ISSUE TITLE
Option to export scene with neutral OID in not used areas

### ISSUE THREAD

**Issue by Somebodyisnobody** [ChristophSilge/TipToiGui#4]
A few days ago I asked on the mailing list what the neutral OID code on the Ravensburger books was like. This code is read by the pen, but is ignored in further processing. It turned out that [the code in raw format is 65535](https://github.com/entropia/tip-toi-reveng/wiki/PEN-Optical-ID-and-codes#oid-codes-used-by-tttool). Thanks to @nomeata for helping.
As the ToiToiGui want's to be handled easy an option to export scenes with neutral background would be nice. For people who want to postprocess the exported files with an external editor it would be nice to have an option which creates one file with the mask (used areas) and one with the inverted mask (the one with the neutral areas).
So by clicking on the export button
![grafik](https://user-images.githubusercontent.com/35230554/100476628-603aa700-30e6-11eb-818a-500b5a092c26.png)
a window could appear:
![grafik](https://user-images.githubusercontent.com/35230554/100477249-1357d000-30e8-11eb-9885-4aece26f9b67.png)

Later this windows can be used for more like the export path.

**Comment by nub1604** [comment]
Good Idea! I will implement this feature
