### ISSUE TITLE
Changing audio source file of media entity is not kept

### ISSUE THREAD

**Issue by Somebodyisnobody** [ChristophSilge/TipToiGui#5]
Steps to reproduce:
- build a logic like shown on the picture
![grafik](https://user-images.githubusercontent.com/35230554/100477421-97aa5300-30e8-11eb-990e-e3cb970ec983.png)
- change the audio file
- [optional] save project
- load project from recent

Produces:
The file change is not applied while the media entity is connected to the sequence.

Suggestion:
At least a warning should appear that notices the user to first disconnect the entities. Optimal solving is to allow changing without disconnecting the entities.

**Comment by nub1604** [comment]
I see the Media-Node folder sync seems to be a bad idea. I have to think about a better solution.
Maybe it will be better to manage the media files via an importer.
So I also can validate names and audio formats.

**Comment by Somebodyisnobody** [comment]
An importer is more code but would be more secure to such things. You could import files as base64 and save it directly into the json-config or you zip the config + all ressources and change the file extension. This is my preferred way as I don't need to b64-decode files when I want to hear them or replace externally.

**Comment by nub1604** [comment]
I want to keep the project file as small as possible. So I Import the media files and rename it if needed, then copy it into the audio folder. Playing around with this folder manually falls out of the guarantor line.

**Comment by Somebodyisnobody** [comment]
I thought about using the CRC32 checksum of the file as internal name. But this would force the GME export by TipToiGui, because it would be too much work to create a GME manually. The whole thing would be a bit proprietary
