### ISSUE TITLE
OID-Codes not displayed in standard window size

### ISSUE THREAD

**Issue by Somebodyisnobody** [ChristophSilge/TipToiGui#7]
Steps to reproduce:
- create one or multiple OIDs
- open graphics editor -> see first image
- then maximize the window -> see second image

Produces:
The UI seems to overlap with the OID-code list
![grafik](https://user-images.githubusercontent.com/35230554/100478454-89116b00-30eb-11eb-84fb-b602d132f6af.png)
![grafik](https://user-images.githubusercontent.com/35230554/100478528-c249db00-30eb-11eb-9639-241134a35696.png)

**Comment by nub1604** [comment]
I found the problem, thanks
